### ISSUE TITLE
CMake Issue

### ISSUE THREAD

**Issue by spectraldecomp** [gtfactslab/CrazySim#11]
![image](https://github.com/gtfactslab/CrazySim/assets/98125550/b25f6816-22c6-42ce-aa70-ed92ed99e2c9)

Hello,

I get the above error when running

``cd crazyflie-firmware``

``mkdir -p sitl_make/build && cd $_``

``cmake ..``

``make all``

Thanks!

**Comment by llanesc** [comment]
Run this command
```bash
sudo apt install python-is-python3
```

**Comment by spectraldecomp** [comment]
I tried so many ways of aliasing, thanks so much!
