### ISSUE TITLE
problem with build and lapack library

### ISSUE THREAD

**Issue by matheeusper** [gtfactslab/CrazySim#7]
![image](https://github.com/gtfactslab/CrazySim/assets/126926145/14c2c4a5-5e98-48b9-93d8-cd972c522656)
i'm trying run your project SITL. But doesn't work, and i don't know how fix, did you has how can i fix that?

**Comment by DexterZzz1010** [comment]
@matheeusper  try this
`sudo apt-get install liblapacke-dev`

**Comment by matheeusper** [comment]
work! but now i have the error:
![image](https://github.com/gtfactslab/CrazySim/assets/126926145/101e552e-a71a-4589-af0a-a7392d31f1d6)

**Comment by DexterZzz1010** [comment]
Maybe you also have to install opencv. But I didn't meet this error before.

**Comment by llanesc** [comment]
Going to close this. Should be fixed in e6afa2941a248129cd7668af45b99f28af8870b3 after removing unnecessary dependencies.
